### ISSUE TITLE
Bot crashes on /stop

### ISSUE THREAD

**Issue by DoctorAnon** [eritislami/evobot#1096]
I get this result and the bot stops functioning WHENEVER i use the /stop command. Everytime i use the stop command, the bot immediately crashes,

home/server/evobot/include/play.js:72
          module.exports.play(queue.songs[0], message, queue.songs[0].url == lastSong.url);
                                                                      ^

TypeError: Cannot read properties of undefined (reading 'url')
    at StreamDispatcher.<anonymous> (/home/server/evobot/include/play.js:72:71)
    at StreamDispatcher.emit (node:events:402:35)
    at finish (node:internal/streams/writable:751:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Velosofy** [comment]
This is confirmed, the bot will crash if you tried to use the `stop` command while `loop` is on

Temporary Fix:
Turn off loop before using `stop`

**Comment by eritislami** [comment]
Hello, I have pushed a commit that might resolve this issue 5e4b2299e82fd461cd63eba58a157a0cac2e3db6 please let me know if it's ok or not, thanks.

**Comment by Velosofy** [comment]
Hello to you too :D, the bot sadly still crashing with `loop` on
![image](https://user-images.githubusercontent.com/61261357/151334818-41fea1e4-d60c-4919-b059-e16ae88383a0.png)

**Comment by eritislami** [comment]
> There's a PR about this from December 2021 #1059
> 
> EDIT : I tested the changes in the PR and it worked - the bot no longer crash

Thanks
