### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'members')🐛 

### ISSUE THREAD

**Issue by lexrivera** [eritislami/evobot#1538]
**Describe the bug**
As seen in the title, this error occurs when attempting to use the bot via slash commands in discord.
**How To Reproduce**
1. Run evobot as normal
2. Use a slash command
 
**Expected behavior**
I followed all the installation steps, I expected the bot to work.  Error on my end somewhere, maybe bad config on discord development portal?  Idk.

**Environment (add if possible)**
* Node.js version: 20.3.1

**Additional information & screenshots**
![Discord_Mr3D31PJM9](https://github.com/eritislami/evobot/assets/85370579/06b2c743-ef83-4a6d-afa4-f62a7e9803b7)
![ubuntu_A7S2EDbBih](https://github.com/eritislami/evobot/assets/85370579/487f8512-c668-4811-b5ac-b013e1bf7568)

**Comment by lexrivera** [comment]
I noticed this issue was brought up previously through the docker implementation and I'm experiencing the same problem through that method as well.  All "Privileged Gateway Intents" boxes are checked in the Discord Developer Portal, I've also invited the bot to the server.  Not sure where I went wrong.
![ubuntu_iXQfEIzN5h](https://github.com/eritislami/evobot/assets/85370579/8240bf21-29b5-43ad-a943-bf3042e90985)

**Comment by eritislami** [comment]
This happens when the bot can't access the server details to read the members. I believe it should be resolved as of latest release

**Comment by andretg12** [comment]
I just downloaded latest release and still see this for some reason

**Comment by xylude** [comment]
I'm also having this issue. I can't seem to get any open source music bots working. I've noticed that it is only in the 'integrations' section of my server settings and doesn't actually show up as a member of the server in the members list. It seems as if it's installing as an application but not a bot and I'm not familiar enough with discord to know what exactly I'm doing wrong. Any help is appreciated!

**Comment by xylude** [comment]
I found my issue: I was adding the bot to the server via the non-bot invite link. I needed to invite the bot to the server via the oauth page.
